name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: robticorg/robtic-actions/.github/workflows/bun-ci.yml@main
    with:
      commit-msg: ${{ github.event.head_commit.message || github.event.pull_request.title }}
      build-command: ""
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CI }}