name: Discord Activity Notifications

on:
  watch:
    types: [started]
  fork:

jobs:
  notify:
    name: Notify Discord
    uses: robticorg/robtic-actions/.github/workflows/reusable-notify.yml@main
    with:
      notification_type: activity
      username: 'Robtic GitHub'
      footer_text: 'Robtic GitHub Activity'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ACTIVITY }}
